### ISSUE TITLE
ExcelFiles v0.2.0 is incompatible with DataFrames v0.11 and prevents a DataFrames upgrade to v0.11.

### ISSUE THREAD

**Issue by ltf-canada** [davidanthoff/ExcelFiles.jl#3]
Occurs on Julia v0.6.1

**Comment by davidanthoff** [comment]
Yep, on my radar.

**Comment by ltf-canada** [comment]
Pretty sure it was. However it was requested that I open issues for any packages that inhibited upgrade to DataFrames v0.11.

**Comment by juliohm** [comment]
Hi @davidanthoff is there a branch that we can clone for DataFrames v.0.11 and beyond?

**Comment by davidanthoff** [comment]
Not yet. I'm working on it, though :) The issue is actually not here, but over in https://github.com/davidanthoff/ExcelReaders.jl.
